POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Titulo novo 6",
    "details": "Um evento para quem gosta de programar",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/c59ffd78-ee57-45aa-bc4b-704c501df436/attendees
Content-Type: application/json

{
    "name": "Pedro Fagundes",
    "email": "pedro889@gmail.com.br"
}

###

GET http://localhost:3333/attendee/8/badge
Content-Type: application/json

{
    
}

